#!/usr/bin/env python3

"""
UpSet plot of differentially expressed genes from run_deseq2.R

INPUTS
------
--dea
    Comma-separated paths to DEA files generated by run_deseq2.R
    Must have following fields: gene_id, log2FoldChange, padj
    Files name must follow this convention:
        DEA_<nominator>_vs_<denominator>.tsv
        or
        DEA_<nominator>_vs_<denominator>_annotated.tsv
--p_thr
    Significance threshold (BH-adjusted p value)
"""

### IMPORTS -------------------------------- ###

import matplotlib.pyplot as plt
import pandas as pd
import upsetplot

from sys import argv

### FUNCTIONS ------------------------------ ###

def parse_args():
    
    # DEA analysis files
    dea_files = argv[argv.index('--dea') + 1].split(',')
    
    # Significance threshold
    p_thr = float(argv[argv.index('--p_thr') + 1]) if '--p_thr' in argv else 0.05
    
    return dea_files, p_thr

### ---------------------------------------- ###

### MAIN ----------------------------------- ###

if __name__ == '__main__':
    
    # Parse CLI args
    dea_files, p_thr = parse_args()
    
    # Load dea files
    dea_data = pd.DataFrame({col : [] for col in ['gene_id', 'log2FoldChange', 'padj', 'origin']})
    for file in dea_files:
        try:
            file_id = file.split('/')[-1].replace('DEA_', '').replace('_annotated.tsv', '').replace('.tsv', '')
            raw_data = pd.read_csv(file, sep='\t')
            raw_data = raw_data.loc[raw_data['padj'] < p_thr, ['gene_id', 'log2FoldChange', 'padj']]
            raw_data = raw_data.sort_values(by='log2FoldChange', ascending=False)
            raw_data.loc[:, 'origin'] = [f'{file_id}_{"upreg" if fc > 0 else "downreg"}' for fc in raw_data['log2FoldChange'].values]
            dea_data = pd.concat([dea_data, raw_data], axis=0)
        except:
            continue

    # Create input for UpSet plot
    plot_data = dea_data.pivot(columns='origin', index='gene_id', values='padj')
    plot_data = plot_data.where(plot_data.isna(), True)
    plot_data = plot_data.fillna(False)
    plot_data = plot_data.reset_index(drop=True)
    plot_data = plot_data.groupby(plot_data.columns.tolist()).size()
    
    # Plot
    plt.figure(figsize=(plot_data.shape[0] // 2, plot_data.shape[0] // 4))
    upset = upsetplot.UpSet(plot_data)
    upset.plot()
    plt.tight_layout()
    plt.savefig('upset_plot.png', dpi=300)
    plt.close()
    